trigger:
- production

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self  # Garante que o código é corretamente checado

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build'

- script: npm test
