version: "3.8"
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faithpoint-development
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - API_PORT=${API_PORT}
      - API_SECRET=${API_SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
    ports:
      - "3308:3308" 
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - faithpoint-network
    depends_on:
      - faith-point

  faith-point:
    image: postgres:13.3-alpine
    container_name: faith-point
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - faith-point-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - faithpoint-network

networks:
  faithpoint-network:
    driver: bridge

volumes:
  faith-point-data:
