import '@modules/shared/logException/infra/container/index';
import '@modules/shared/country/infra/container/index';
import '@modules/shared/state/infra/container/index';
import '@modules/shared/city/infra/container/index';
import '@modules/shared/address/infra/container/index';
import '@modules/role/infra/container/index';
import '@modules/user/infra/container/index';
import '@modules/auth/infra/container/index';
import '@modules/logAuth/infra/container/index';