name: Delete Merged Branches (Test)

on:
  push:
    branches:
      - feature/deleteBranches

jobs:
  delete_merged_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Delete Merged Branches
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global init.defaultBranch production
          git fetch --all

          # Set up Git to use the personal access token
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git

          # Define branch patterns to delete
          BRANCH_PATTERNS=("origin/feature/" "origin/hotfix/" "origin/fix/" "origin/chore/" "origin/docs/" "origin/release/")
          
          for PATTERN in "${BRANCH_PATTERNS[@]}"; do
            BRANCHES=$(git branch -r | grep "$PATTERN" | grep -v 'origin/feature/deleteBranches')
            for BRANCH in $BRANCHES; do
              BRANCH_NAME=${BRANCH#*/}
              if ! git branch -r --contains origin/feature/deleteBranches | grep -q $BRANCH_NAME; then
                echo "Deleting branch: $BRANCH_NAME"
                git push origin --delete $BRANCH_NAME
              fi
            done
          done
