name: Delete Merged Branches

on:
  push:
    branches:
      - production

jobs:
  delete_merged_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Merged Branches
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global init.defaultBranch production
          git fetch --all

          # Define branch patterns to delete
          BRANCH_PATTERNS=("origin/feature/" "origin/hotfix/" "origin/fix/" "origin/chore/" "origin/docs/" "origin/release/")
          
          for PATTERN in "${BRANCH_PATTERNS[@]}"; do
            BRANCHES=$(git branch -r | grep "$PATTERN" | grep -v 'origin/production')
            for BRANCH in $BRANCHES; do
              BRANCH_NAME=${BRANCH#*/}
              if ! git branch -r --contains origin/production | grep -q $BRANCH_NAME; then
                echo "Deleting branch: $BRANCH_NAME"
                git push origin --delete $BRANCH_NAME
              fi
            done
          done
