name: Build and Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy-develop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: npm ci --force
      - run: npm run build
      - uses: docker/setup-buildx-action@v1
      - run: docker-compose -f docker-compose.develop.yml build 
