name: Build and Deploy Production

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: npm ci --force
      - run: npm run build
      - uses: docker/setup-buildx-action@v1
      - run: docker-compose -f docker-compose.production.yml --build
