name: Build and Deploy Homolog

on:
  push:
    branches:
      - homolog

env:
  AWS_PUBLIC_IP: ${{ secrets.HOMOLOG_AWS_PUBLIC_IP }}
  AWS_USERNAME: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SSH_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-deploy-homolog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: npm ci --force
      - run: npm run build
      - uses: docker/setup-buildx-action@v1
      - run: docker-compose -f docker-compose.homolog.yml build
      - uses: appleboy/scp-action@master
        with:
          host: ${{ env.AWS_PUBLIC_IP }}
          username: ${{ env.AWS_USERNAME }}
          key: ${{ env.AWS_SSH_KEY }}
          source: .
          target: /path/to/app
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_PUBLIC_IP }}
          username: ${{ env.AWS_USERNAME }}
          key: ${{ env.AWS_SSH_KEY }}
          script: |
            cd /path/to/app
            docker-compose -f docker-compose.homolog.yml down
            docker-compose -f docker-compose.homolog.yml up -d
