name: Build and Deploy Homolog

on:
  push:
    branches:
      - homolog

jobs:
  build-and-deploy-homolog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: npm ci --force
      - run: npm run build
      - uses: docker/setup-buildx-action@v1
      - run: docker-compose -f docker-compose.homolog.yml --build
